### ISSUE TITLE
Windows - yarn install ends with errors

### ISSUE THREAD

**Issue by petrvecera** [MainframeHQ/js-mainframe#126]
Hi guys

There is an issue with `yarn install` on Windows. These issues are around packages `scrypt`, `sha3`. This is example error:
```
[4/6] ? scrypt
error C:\Users\Administrator\Documents\js-mainframe\node_modules\scrypt: Command
 failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: C:\Users\Administrator\Documents\js-mainframe\node_modules\scrypt
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.13.0 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Administrator\Document
s\js-mainframe\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Administrator\Documents
\js-mainframe\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Users\Administrator\Documents\js-mainframe\node_modules
\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator
\\Documents\\js-mainframe\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Administrator\Documents\js-mainframe\node_modules\scrypt
gyp ERR! node -v v10.13.0
```
I have verified the issue on clean install of Windows with just Node 10 and latest Yarn.
These issues may be common and similar one is reported here: https://github.com/ethereum/web3.js/issues/1066 

**Workaround:**
To fix this I had to do 2 things:
- Install python 2 and make sure that `python` command leads to it
- Install `yarn global add windows-build-tools` make sure you are in window with Admin rights, this step may take more than 30 minutes

With these 2 steps you can finish the `yarn install` command without the errors. However I run into other errors and incompatibilities on Windows platform so for now I would recommend trying it out in Linux.

**Comment by cayblood** [comment]
@petrvecera Thanks for submitting this! We are currently getting some Windows hardware so that we can test this stuff more thoroughly.
